# spring.application.name=iDelivery-Gateway

server.port: 9999

spring:
  application:
    name: iDelivery-Gateway

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 10 #ms
            response-timeout: 300ms

          routes:
            # Route for Delivery Tracking
            - id: delivery-tracking-route
              uri: lb://delivery-tracking
              predicates:
                - Path=/api/v1/deliveries/**
                - Method=GET,POST,PUT,DELETE,OPTION
              filters:
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
                    method: GET,PUT
                    backoff: 
                      first-backoff: 10ms
                      max-backoff: 30ms 
                      factor: 2
                    timeout: 400ms #test retry
                - name: CircuitBreaker
                  args:
                    name: delivery-tracking-route-circuit-breaker 
                    statusCodes: 
                      - 500
                      - 502
                      - 504

            # Route for Courier Management
            - id: courier-management-route
              uri: lb://courier-management
              predicates:
                - Path=/api/v1/couriers/**

            - id: courier-management-public-route
              uri: lb://courier-management
              predicates:
                - Path=/public/couriers
                - Method=GET
              filters:
                - RewritePath=/public/couriers, /api/v1/couriers
                - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveriesQuantity,phone,true

            - id: courier-management-public-segments-route
              uri: lb://courier-management
              predicates:
                - Path=/public/couriers/**
                - Method=GET
              filters:
                - RewritePath=/public/couriers/?(?<segment>.*), /api/v1/couriers/$\{segment}
                - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveriesQuantity,phone,true
                
resilience4j:
  circuitbreaker:
    configs:
      default: 
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10000
    instances:
      delivery-tracking-route-circuit-breaker:
        base-config: default
        wait-duration-in-open-state: 5000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
