# spring.application.name=iDelivery-Gateway

server.port: 9999

spring:
  application:
    name: iDelivery-Gateway

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 10 #ms
            response-timeout: 300ms

          routes:
            # Route for Delivery Tracking
            - id: delivery-tracking-route
              uri: lb://delivery-tracking
              predicates:
                - Path=/api/v1/deliveries/**
                - Method=GET,POST,PUT,DELETE,OPTION
              filters:
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
                    method: GET,PUT
                    backoff: 
                      first-backoff: 10ms
                      max-backoff: 30ms 
                      factor: 2
                    timeout: 400ms #test retry

            # Route for Courier Management
            - id: courier-management-route
              uri: lb://courier-management
              predicates:
                - Path=/api/v1/couriers/**

            - id: courier-management-public-route
              uri: lb://courier-management
              predicates:
                - Path=/public/couriers
                - Method=GET
              filters:
                - RewritePath=/public/couriers, /api/v1/couriers
                - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveriesQuantity,phone,true

            - id: courier-management-public-segments-route
              uri: lb://courier-management
              predicates:
                - Path=/public/couriers/**
                - Method=GET
              filters:
                - RewritePath=/public/couriers/?(?<segment>.*), /api/v1/couriers/$\{segment}
                - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveriesQuantity,phone,true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/