# spring.application.name=Delivery-Tracking

server:
  port: 8080

spring:
  application:
    name: Delivery-Tracking

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:delivery-tracking-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          delivery-placement-event:com.example.delivery.tracking.domain.event.DeliveryPlacedEvent,
          delivery-picked-up-event:com.example.delivery.tracking.domain.event.DeliveryPickUpEvent,
          delivery-fulfilled-event:com.example.delivery.tracking.domain.event.DeliveryFulFilledEvent